# Janos Revesz: Session 3

Your task for today is to complete this Jupyter Notebook. 

First, rename this notebook to "Yourname-session3", and change the title in this text cell to "Yourname: Session 3"
(replacing "Yourname" with your actual name...)

Then fill in the blank code and text cells below to answer the questions. 
Remember to:
* include `#comments` in your code cells, and
* where you are asked to complete text cells, make sure you use complete, grammatically correct sentences.

Make sure you run the cell below to import the numpy module.

In [1]:
import numpy as np

## Part 1:


1. `np.array([0,5,10])` will create an array of **_integers_** starting at 0, finishing at 10, with interval 5. Use a different numpy function to create the same array automatically (i.e. choose an appropriate function from the list given in the "Other ways to create arrays" section of the script). Assign this to the variable name `array_a`

In [6]:
array_a = np.linspace(0,10,3)
print(array_a)

[ 0.  5. 10.]


2. Create (automatically, not using np.array!) another array that contains 3 equally-spaced floating point numbers starting at 2.5 and finishing at 3.5. Assign this to the variable name `array_b`.

   Then use array slicing to output the second element of this array.

In [4]:
array_b = np.linspace(2.5,3.5,3)
print(array_b)

[2.5 3.  3.5]


3. Use the multiplication operator `*` to multiply `array_a` and `array_b` together.

In [7]:
array_a*array_b

array([ 0., 15., 35.])

4. Use your awesome google skills to find numpy functions that will find the dot product and the cross product of these two arrays. Use a text cell to comment on the differences between this and using the `*` operator.

In [59]:
print(np.dot(array_a, array_b))
print(np.cross(array_a, array_b))

50.0
[-12.5  25.  -12.5]


##### STUDENT TEXT CELL: add to this text cell to complete your answer to question 4

The difference between the dot product the cross product and the * product of two arrays is that the * product of the two arrays return a third array which elements are the product of the previous vector's corresponding elements, the dot product adds up the elements of the third array and that's the returned value and the cross product is the same as if we


5. We met the "`while`" loop last week, and mentioned the "`for`" loop. An example of a "`for`" loop is in the cell below. Add comments to this cell *and* complete the text cell below to explain how this works.

In [17]:
# Creates the array called r with its elements being 5 points evenly spaced between 1 and 2.5 including 1 and 5
r = np.linspace(1, 2.5, 5)
# The elements of the array r are printed out
print(r)

# The for loop goes through each element of the array r and prints them out 
#  after that it prints out the element of the array times 3
for n in r:
    print("n is ", n)
    print("n*3 is ", n*3)
    
# After going throught the loop "Finished" is printed out
print("Finished")

[1.    1.375 1.75  2.125 2.5  ]
n is  1.0
n*3 is  3.0
n is  1.375
n*3 is  4.125
n is  1.75
n*3 is  5.25
n is  2.125
n*3 is  6.375
n is  2.5
n*3 is  7.5
Finished


##### STUDENT TEXT CELL: add to this text cell to complete your answer to question 5
for loop:
 the loop starts with the 0th element of the array and finishes with the last elemen, at start n equals to the 0th element of the array, when the loop runs again it equals the first element of the array, the next time it equals the second element of the array and so on, basically it changes it's value to the next value of the array each time the for loop runs


## Part 2:

For this part of the task you will be working with the "wheat spike" example you saw in the first PHAS0007 "Data Analysis and Statistics" lecture, and use Python to reproduce some of the calculations you saw there.

You'll probably want to consult the lecture slides on Dr Llorente Garcia's Moodle as well as the PHAS0007 Data Analysis Booklet.

Download the file "wheatdata.txt" from Moodle and save it in the same directory as your Notebook. This data file contains the same data as on slide 11 of the lecture slides.

1. Use the code cell below to:
    * Import the data from this file into an array using `np.loadtxt()` - choose your own (sensible) variable name for this array.
    * Print out the array with an appropriate text string.

In [47]:
# We export the data from wheatdata.txt, each data element of the txt is a value of the array exported_data
exported_data = np.loadtxt("wheatdata.txt")
print("The values of wheatdata.txt: ",exported_data)

The values of wheatdata.txt:  [533. 440. 484. 446. 474. 492. 512. 515. 528. 572.]


2. Using information from the data analysis booklet or google, find the appropriate numpy function to calculate the mean number of spikes in each patch. Calculate this in the cell below, and again, output this with an appropriate text string.

In [48]:
# Using the numpy library's average() function we average the values of exported_data
average_spike = np.average(exported_data)
print("The average number of spikes in a patch from wheatdata.txt: ", average_spike)

The average number of spikes in a patch from wheatdata.txt:  499.6


3. The formula for the (sample) standard deviation is 
$$ \sigma = \sqrt{\frac{\sum{(x_i - \bar{x})^2}}{N-1}}, $$

   where $N$ is the number of data points and $\bar{x}$ the average you just calculated. 
   
   Use the python function `len()` to calculate a value for $N$ in the cell below, and again, output this with an appropriate text string. Remember, you can use "SHIFT+TAB" with the cursor on a function name to view the documentation for that function.

In [49]:
# Using the len() function we calculate the number of elements in the array exported_data
num_data = len(exported_data)
print("number of data points in wheatdata.txt: ", num_data)

number of data points in wheatdata.txt:  10


We're going to calculate the numerator of the equation for the standard deviation in steps. 

We can calculate the individual deviations $d_i = x_i - \bar{x}$ as in the code cell below. 

You will need to make sure that the variable names here match the variable names you've chosen above.

In [29]:
# Edit the variable names in this cell to match the variable names you have used above
deviations = exported_data - average_spike # calculate individual deviations
print("The individual deviations from the mean are", deviations) # output this value with an appropriate text string

The individual deviations from the mean are [ 33.4 -59.6 -15.6 -53.6 -25.6  -7.6  12.4  15.4  28.4  72.4]


Note how this works: `spike_data` is an array of values, but `mean_spikes` is a single value. Numpy will automatically subtract `mean_spikes` from every element of the array `spike_data`.



5. Now we have calculated the individual deviations, we can square them, then sum them together using `np.sum()`. Do this in the cell below. Make sure you do the squaring and summing  in the right order though!

   Remember to print out the result with an appropriate text string.

In [51]:
# Square each value of the array deviation and make a new array called sqr_deviation with these values
sqr_deviation = np.square(deviations)
# Sum up all the values of sqr_deviation
numerator = np.sum(sqr_deviation)
print("The numerator from the formula of standard deviation: ",numerator)

The numerator from the formula of standard deviation:  14936.400000000001


6. Now you have all the elements you need to calculate the standard deviation using the equation in question 3 above. Do this in the cell below. You should find your answer is close to (but not exactly the same as) the standard deviation calculated in the lecture slides. 

    Remember to print out the result with an appropriate text string. Yes, you will always need to do this.

In [52]:
# Calculate the standard deviation with the numerator calculated above where N = num_data 
standard_deviation =  np.sqrt(numerator/(num_data - 1))
print("The standard deviation of the data from wheatdata.txt: ",standard_deviation)

The standard deviation of the data from wheatdata.txt:  40.738188472243095


That was rather an effort to calculate the standard deviation, and fortunately numpy has a function that will do this for you: `np.std()`.

You do have to be a bit careful with this function, and you're about to see why. Run the cell below, compare the results to what you just calculated above, then read both the [documentation for `np.std()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html) and the information in section 2.6 (p.13) of [Hughes and Hase](https://ebookcentral.proquest.com/lib/ucl/reader.action?docID=584562&ppg=25.) (You may need to sign in with your UCL credentials to access this link).

7. Then use the text cell below to state which version of the standard deviation you should use here, and (briefly) why.

In [53]:
stdev_1 = np.std(exported_data)          # Edit to reflect your chosen variable names
stdev_2 = np.std(exported_data, ddof=1)  # Edit to reflect your chosen variable names

print("Standard deviation: first calculation gives", stdev_1, ", second calculation gives", stdev_2)

Standard deviation: first calculation gives 38.647638996451 , second calculation gives 40.738188472243095


##### STUDENT TEXT CELL: add to this text cell to answer question 7
The second version should be used. In the first version the denumerator is equal to the number of data we use in the second version the denumerator is the number of data we use minus one. 

8. We can also calculate the standard error of the mean, which is given by 
   $$\alpha = \frac{\sigma_{N-1}}{\sqrt{N}}$$
   Apply what you've learned above to calculate this in the cell below. 

In [54]:
# Calculate the standard error of the mean using the values calculated above
# the numerator is standard_deviation and N is num_data
standard_err_mean = standard_deviation/np.sqrt(num_data)
print("The standard error of the mean is: ",standard_err_mean)

The standard error of the mean is:  12.882546332150334


9. Finally, use your google skills to find a python function that will calculate the standard error of the mean for you, and verify that you get the same result when using this function (hint: this function is not in numpy, you will need to import another module!)

In [58]:
from scipy import stats
# Calculate the standard error of the mean using the stats.sem() function from the library scipy
std_err_mean = stats.sem(exported_data)
print("The standard error of the mean is: ", std_err_mean)

The standard error of the mean is:  12.882546332150334
